### PR TITLE
Removes implicit byte conversion in Windows code

### LINKED ISSUE #2: Doesn't work with python 3.5 under windows 10
First thing I noticed were several implicit string conversions, but even after fixing those I still get the following exception:
'The driver cannot recognize the specified command.'

Incorporating the windows code from this library (which works really well but is windows only) could be an idea.  It is licensed under the Apache license according to the python package index.
[https://github.com/michaelgundlach/mp3play](https://github.com/michaelgundlach/mp3play)

### PR DESCRIPTION
**Pull request by guiweber**
Fixes #2

### CODE REVIEW

**Comment by TaylorSMarks** [comment]
Will this break compatibility with Python 2?

**Comment by guiweber** [comment]
I don't think so, but could you test it just to make sure? I don't have Python 2 on my system anymore.

If it does break compatibility, let me know and I'll submit a new pull request adding a conditional clause for the byte conversions.

**Comment by guiweber** [comment]
@TaylorSMarks Any hope of getting this PR merged?

**Comment by TaylorSMarks** [comment]
The computer I uploaded this from died. I haven't set up git on its replacement yet and I'm not sure how to merge pull requests anyways.

Taylor

**Comment by guiweber** [comment]
@TaylorSMarks You can merge a pull request directly from Github. There should be a big green button that says something like "merge pull request" near the bottom of the pull request page: https://github.com/TaylorSMarks/playsound/pull/3

cheers!

**Pull request merged**
