### PR TITLE
Institutes garbage collection to close files which have finished playing in Windows.

### PR DESCRIPTION
**Pull request by garydavenport73**
In Windows - 

- every time there is a call to play a sound, a garbage collection function looks through a list of previous sounds that have not been closed.  If they have finished playing, they are closed, then removed from the garbage collection list.

### CODE REVIEW

**Review by garydavenport73 — COMMENTED** [review]
Placing garbage collection list creation and function call after file is able to be open and played.

**Comment by garydavenport73** [comment]
Utilizing garbage collection function.  Checks to see if previously played files are still playing, if not they are closed.  Runs every time a sound is played.

**Review by TaylorSMarks — CHANGES_REQUESTED** [review]
I have a lot of concerns with this PR.

1 - Is it actually fixing anything? There's no changes to the unit tests.
2 - Is it thread safe? It seems like multiple threads could be running the collectGarbage function at the same time.
3 - The list traversal is non-pythonic... if you really need the index, use the enumerate function, but I don't think it's really needed... wouldn't using a set instead of a list work fine/better?
4 - The reverse list traversal is even weirder and less-pythonic - there are proper ways to go over it backwards, but a set would remove concerns about that... also, I don't think those concerns apply here since you're not modifying removalList while traversing it (you're modifying garbageCollection).
5 - Why are all exceptions being silently swallowed?
6 - try: pass except: makes absolutely no sense - the try does nothing and can never throw an exception, so the except block will never fire. The entire thing may as well not exist and should be removed.

**Comment by garydavenport73** [comment]
Hi Taylor,
1 - I was trying to fix closing the sounds after they are opened.  I
thought this was needed to deallocate memory.
2 - I didn't test this, but I think so.  I have played multiple sounds
immediately one after another without issues, so I assumed
that issuing commands to close a sound in succession would be safe.
3 - I just used a list because I see them used more commonly.  There is
certainly more than one approach.  I tend to think of it
in terms of a list because they do actually start in a sequential order.
Thank you for suggesting this.  I am going to study and learn
about this more.
4 - I see you are right, going backwards is not necessary, thank you for
pointing that out.
5 - I should not have done that.  That should be undone.
6 - I agree

I will delete the pull request.

I kind of assumed issuing close statements are supposed to happen since the
winmm.dll
documentation says to close them, the memory is allocated using c, so I
assumed that manual garbage collection is needed.

Overall, do you want me to work on making the sounds close?

If you think it is needed, I think the idea of keeping track of sounds,
checking to see if they are finished,
and closing them if they are finished should be straight-forward (maybe I
am naive about this).

If you think this is not needed or don't want me to work on it please let
me know and I will stop working on it.

Best regards and thank you for the time and effort you have put into this
module.
Gary

**Comment by TaylorSMarks** [comment]
If you’re going to work on this then I’d like proof that something is wrong. Add a unit test that fails with the code currently on master which you can fix.

I’d think running some background thread that closes the sound after it’s done playing would be better than managing a collection of garbage that needs to be closed and checking it everytime playsound is used.

Thanks,
Taylor

**Pull request closed without merging**
