### PR TITLE
Compliance with PEP 517

### LINKED ISSUE #131: Releasing new Pypi version
Hello,

first of all thank you for developing this library! Audio is difficult 🙈.

I think it would be a great idea to release a new version on Pypi, because this code for example:
```python
import playsound
import logging

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    FILENAME = "ROME – Parlez-Vous Hate (Full Song).mp3"
    playsound.playsound(FILENAME)
```
works on the Git version, but not in 1.3.0 released on Pypi due to the special characters in the string. (It causes Error 305.)

Have a great day!

### LINKED ISSUE #143: Installation error: error: subprocess-exited-with-error,  OSError: could not get source code
Hello, I'm trying to install playsound on my mac running Python 3.9 and getting the following error. Any suggestions how to fix?

```
chrisrogers@356556745867867 ~ % pip install playsound                                   
Collecting playsound
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fv/5wd8td9d4d38tqwm7ldnjm6c0000gn/T/pip-build-env-x4qmfqab/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fv/5wd8td9d4d38tqwm7ldnjm6c0000gn/T/pip-build-env-x4qmfqab/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fv/5wd8td9d4d38tqwm7ldnjm6c0000gn/T/pip-build-env-x4qmfqab/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fv/5wd8td9d4d38tqwm7ldnjm6c0000gn/T/pip-build-env-x4qmfqab/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/inspect.py", line 1262, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/inspect.py", line 1244, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "/Users/chrisrogers/.pyenv/versions/3.11.3/lib/python3.11/inspect.py", line 1081, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

### LINKED ISSUE #145: Playground exit code: 1 when installing playground on python311 pip23.1.2
>pip install playground --user

Collecting playsound
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Roger Henley\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-env-5dwznkuv\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-env-5dwznkuv\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-env-5dwznkuv\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Usersxxxxx\AppData\Local\Temp\pip-build-env-5dwznkuv\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Python311\Lib\inspect.py", line 1270, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\inspect.py", line 1252, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\inspect.py", line 1081, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

I assume this is a playsound issue.  Is there a fix?

### LINKED ISSUE #148: Compliance with PEP 517
The setuptools is treating [setup.py as legacy](https://pip.pypa.io/en/latest/reference/build-system/setup-py) after introducing pyproject.toml in [PEP 517](https://peps.python.org/pep-0517) and [PEP 518](https://peps.python.org/pep-0518).

### LINKED ISSUE #150: pip install playsound no longer works
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  note: This error originates from a subprocess, and is **likely not a problem with pip.**
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is **likely not a problem with pip.**
      
 Here is what i have tried:
pip install --upgrade setuptools
pip install --upgrade wheel
python --m pip install playsound 
python.exe -m pip install --upgrade pip

Also this is not an error with PIP as statedd above in the bolded text

### PR DESCRIPTION
**Pull request by ghost**
Closes #150
Closes #148
Closes #145
Closes #143
Closes #131

### CODE REVIEW

**Comment by ghost** [comment]
Hey 👋
Is there anything missing for this PR to be merged?

**Comment by JAEarly** [comment]
+1 to merge this in!

**Comment by ghost** [comment]
Just install `wheel` and you probably won't have any more errors during the installation, I don't know if this PR is still valid since playsound supports python 2 and I don't know if this new installation would work in these versions that python no longer supports

**Comment by ghost** [comment]
Closed due to inactivity

**Pull request closed without merging**
