### PR TITLE
Close windows stream after playing sound

### PR DESCRIPTION
**Pull request by driedler**
This fixes a bug where the windows stream isn't closed after playing the sound

### CODE REVIEW

**Comment by portasynthinca3** [comment]
I think this PR has to be merged as it causes a memory leak.
A related issue in one of my projects: https://github.com/portasynthinca3/ppfun2/issues/1

**Comment by TaylorSMarks** [comment]
@portasynthinca3 - What this project really needs is automated tests.

I used to just accept PRs but I found that they often caused regressions. 

I stopped using the code personally several years ago, so maintaining it fell to nonexistent on my priority list.

Somebody forked it to make boombox - I think they’re more actively maintaining that, so you might want to switch to it.

**Comment by portasynthinca3** [comment]
Ah, that makes sense. Thanks for pointing me in the right direction.

**Comment by Zx-EvM** [comment]
@TaylorSMarks that issue is critical for working your module on Windows correctly. This issue causes a memory leak and your module exits with the following error:

```
Not enough memory available for this task.

Quit one or more applications to increase available memory, and then try again.
```

Note that in project by which yours inspired by has the same `close` functionality such the PR offers: https://github.com/michaelgundlach/mp3play/blob/master/mp3play/windows.py#L82

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testNonBlockingRepeat, which should ensure that it doesn't regress.

**Review by McSnurtle — COMMENTED** [review]
Looks good, plz merge

EDIT: oh

**Pull request closed without merging**
